#include "common.hpp"
#include <boost/test/unit_test.hpp>

#include <iostream>
#include <memory>
#include "../include/MinHashSketch.hpp"

BOOST_AUTO_TEST_SUITE(TestMinhashSketch)

BOOST_AUTO_TEST_CASE(TestConstructor)
{

    const std::string s("TTGGTATGCTTCGTTCAGTTTCAGGTTTGGGTGTTTAACCGTTTTTTCACATTTATCGTGAAACGCTTTCGCGTTTTCGTGCCGCTTCAGCTCTGGAAATCGACCTGACGGGGTCGGTGGAGAACGATTATTTTTCTGTAATGAGCAGAACGAAAAGGTGGTGGTCACTGGCAGGGGCGACAGTATCCAGCCGTATCCCATTCCAGGAGTTTTTGAACTGAATGGCAAAGGCACCAGTACGCGCCCACGCTGACGGTTTCTAACCTGTACGGTATGGTCACCCGGGATGGCGGAAGATATGCGAAGTCTGGTCAGCCGGAACGGTCCGGCGTAGGTTCGCCGTTTTCTGGATGCGGTGAACCGTCAGCGAAACAGTTACGCCGTCCGGAGCAGGGTGATCAGCCGCTGGCGCACTGAGCAGTGCAGCAGACGAGCGCGGTGATTACCTCACTTTGCCAGTCCCGCCGACGGAAACGGATGGCGCTGTTTTCAGGACGTCATGCTGGCCAGCACCTGCACC");
    MinHashSketch m1{s, 16, 512, false, 0.9};

    auto &r = m1.getMinHashArray();

    BOOST_CHECK_EQUAL(r.size(), 512UL);
}

BOOST_AUTO_TEST_SUITE_END()
